import { Partner } from "./types";

// Affiliate URLs: vervang deze met echte Daisycon trackinglinks uit jouw account
// Formaat: https://bdt9.net/c/?si=ADVERTISER_ID&li=MATERIAL_ID&wi=419930
// wi=419930 is jouw publisher website ID (VoltigeverenigingDeWittegheit)

export const partners: Partner[] = [
  {
    id: "bol",
    name: "bol.com",
    logoUrl: "https://www.google.com/s2/favicons?domain=bol.com&sz=64",
    description: "Nederland's grootste online winkel voor boeken, electronica, speelgoed en meer.",
    categories: ["Boeken, Literatuur & Media", "Electronica"],
    affiliateUrl: "https://bdt9.net/c/?si=1234&li=5678&wi=419930",
    commission: "2–4%",
    tags: ["webshop", "boeken", "electronica", "speelgoed", "games"],
    featured: true,
  },
  {
    id: "coolblue",
    name: "Coolblue",
    logoUrl: "https://www.google.com/s2/favicons?domain=coolblue.nl&sz=64",
    description: "Alles voor een glimlach. Electronica, witgoed en meer met gratis bezorging.",
    categories: ["Electronica"],
    affiliateUrl: "https://bdt9.net/c/?si=1235&li=5679&wi=419930",
    commission: "1–3%",
    tags: ["electronica", "witgoed", "telefoons", "laptops", "tv"],
    featured: true,
  },
  {
    id: "zalando",
    name: "Zalando",
    logoUrl: "https://www.google.com/s2/favicons?domain=zalando.nl&sz=64",
    description: "Meer dan 2000 merken mode, schoenen en accessoires. Gratis levering en retour.",
    categories: ["Mode & Kleding"],
    affiliateUrl: "https://bdt9.net/c/?si=1236&li=5680&wi=419930",
    commission: "4–7%",
    tags: ["kleding", "schoenen", "mode", "fashion", "accessoires"],
    featured: true,
  },
  {
    id: "booking",
    name: "Booking.com",
    logoUrl: "https://www.google.com/s2/favicons?domain=booking.com&sz=64",
    description: "Hotels, vakantiehuizen en meer wereldwijd. Boek met gratis annulering.",
    categories: ["Reizen"],
    affiliateUrl: "https://bdt9.net/c/?si=1237&li=5681&wi=419930",
    commission: "4%",
    tags: ["hotels", "reizen", "vakantie", "accommodatie"],
    featured: true,
  },
  {
    id: "decathlon",
    name: "Decathlon",
    logoUrl: "https://www.google.com/s2/favicons?domain=decathlon.nl&sz=64",
    description: "Sport voor iedereen. Goedkope en kwaliteitsvolle sportartikelen voor alle sporten.",
    categories: ["Sport & Outdoor"],
    affiliateUrl: "https://bdt9.net/c/?si=1238&li=5682&wi=419930",
    commission: "3–5%",
    tags: ["sport", "outdoor", "fitness", "wielrennen", "paardensport", "rijkleding"],
    featured: true,
  },
  {
    id: "ikea",
    name: "IKEA",
    logoUrl: "https://www.google.com/s2/favicons?domain=ikea.com&sz=64",
    description: "Meubelen en woonaccessoires voor een mooi thuis voor een lage prijs.",
    categories: ["Wonen, Huis & Tuin"],
    affiliateUrl: "https://bdt9.net/c/?si=1239&li=5683&wi=419930",
    commission: "3%",
    tags: ["meubels", "wonen", "interieur", "keuken", "slaapkamer"],
  },
  {
    id: "mediamarkt",
    name: "MediaMarkt",
    logoUrl: "https://www.google.com/s2/favicons?domain=mediamarkt.nl&sz=64",
    description: "De laagste prijs voor electronica, witgoed en entertainment.",
    categories: ["Electronica"],
    affiliateUrl: "https://bdt9.net/c/?si=1240&li=5684&wi=419930",
    commission: "1–2%",
    tags: ["electronica", "tv", "audio", "smartphones", "gaming"],
  },
  {
    id: "thuisbezorgd",
    name: "Thuisbezorgd.nl",
    logoUrl: "https://www.google.com/s2/favicons?domain=thuisbezorgd.nl&sz=64",
    description: "Bestel eten bij restaurants in jouw buurt. Snel bezorgd aan de deur.",
    categories: ["Eten & Drinken"],
    affiliateUrl: "https://bdt9.net/c/?si=1241&li=5685&wi=419930",
    commission: "3–5%",
    tags: ["eten", "bezorging", "restaurants", "maaltijden", "thuis"],
  },
  {
    id: "wehkamp",
    name: "Wehkamp",
    logoUrl: "https://www.google.com/s2/favicons?domain=wehkamp.nl&sz=64",
    description: "Mode, wonen en meer. Al 75 jaar jouw betrouwbare online warenhuis.",
    categories: ["Mode & Kleding", "Wonen, Huis & Tuin"],
    affiliateUrl: "https://bdt9.net/c/?si=1242&li=5686&wi=419930",
    commission: "5–8%",
    tags: ["mode", "kleding", "wonen", "meubels", "kinderen"],
  },
  {
    id: "vidaxl",
    name: "vidaXL",
    logoUrl: "https://www.google.com/s2/favicons?domain=vidaxl.nl&sz=64",
    description: "Meubels, tuin en buitenleven voor de laagste prijs. Meer dan 50.000 producten.",
    categories: ["Wonen, Huis & Tuin"],
    affiliateUrl: "https://bdt9.net/c/?si=1243&li=5687&wi=419930",
    commission: "3–6%",
    tags: ["tuin", "meubels", "buiten", "bbq", "schommel", "paardenstal"],
  },
  {
    id: "amazon",
    name: "Amazon.nl",
    logoUrl: "https://www.google.com/s2/favicons?domain=amazon.nl&sz=64",
    description: "Miljoenen producten van A tot Z. Snel geleverd met Prime.",
    categories: ["Boeken, Literatuur & Media", "Electronica"],
    affiliateUrl: "https://bdt9.net/c/?si=1244&li=5688&wi=419930",
    commission: "3–10%",
    tags: ["alles", "boeken", "electronica", "prime", "amazon"],
  },
  {
    id: "sportmaster",
    name: "Sport2000",
    logoUrl: "https://www.google.com/s2/favicons?domain=sport2000.nl&sz=64",
    description: "Specialist in sportartikelen voor recreatief en professioneel sporten.",
    categories: ["Sport & Outdoor"],
    affiliateUrl: "https://bdt9.net/c/?si=1245&li=5689&wi=419930",
    commission: "4–6%",
    tags: ["sport", "voetbal", "hardlopen", "fitness", "outdoor"],
  },
  {
    id: "hm",
    name: "H&M",
    logoUrl: "https://www.google.com/s2/favicons?domain=hm.com&sz=64",
    description: "Mode voor de hele familie. Trendy kleding voor dames, heren en kinderen.",
    categories: ["Mode & Kleding", "Kinderen & Ouders"],
    affiliateUrl: "https://bdt9.net/c/?si=1246&li=5690&wi=419930",
    commission: "6–8%",
    tags: ["mode", "kleding", "fashion", "kinderkleding", "heren", "dames"],
  },
  {
    id: "travelbird",
    name: "TravelBird",
    logoUrl: "https://www.google.com/s2/favicons?domain=travelbird.nl&sz=64",
    description: "Dagelijkse deals voor stedentrips en weekendjes weg in Europa.",
    categories: ["Reizen"],
    affiliateUrl: "https://bdt9.net/c/?si=1247&li=5691&wi=419930",
    commission: "5%",
    tags: ["reizen", "stedentrip", "vakantie", "deals", "europa"],
  },
  {
    id: "kruidvat",
    name: "Kruidvat",
    logoUrl: "https://www.google.com/s2/favicons?domain=kruidvat.nl&sz=64",
    description: "Drogisterij met duizenden producten voor gezondheid, beauty en verzorging.",
    categories: ["Gezondheid & Beauty"],
    affiliateUrl: "https://bdt9.net/c/?si=1248&li=5692&wi=419930",
    commission: "3–5%",
    tags: ["gezondheid", "beauty", "verzorging", "drogisterij", "vitaminen"],
  },
  {
    id: "fonq",
    name: "Fonq",
    logoUrl: "https://www.google.com/s2/favicons?domain=fonq.nl&sz=64",
    description: "Design wonen en lifestyle producten. Unieke merken voor je interieur.",
    categories: ["Wonen, Huis & Tuin"],
    affiliateUrl: "https://bdt9.net/c/?si=1249&li=5693&wi=419930",
    commission: "5–8%",
    tags: ["design", "wonen", "interieur", "lifestyle", "keuken"],
  },
  {
    id: "etos",
    name: "Etos",
    logoUrl: "https://www.google.com/s2/favicons?domain=etos.nl&sz=64",
    description: "Jouw persoonlijke verzorgingsspecialist. Huidverzorging, haarverzorging en meer.",
    categories: ["Gezondheid & Beauty"],
    affiliateUrl: "https://bdt9.net/c/?si=1250&li=5694&wi=419930",
    commission: "3–4%",
    tags: ["beauty", "huidverzorging", "haar", "cosmetica", "parfum"],
  },
  {
    id: "kwantum",
    name: "Kwantum",
    logoUrl: "https://www.google.com/s2/favicons?domain=kwantum.nl&sz=64",
    description: "Gordijnen, vloerbedekking en woonaccessoires voor een mooi interieur.",
    categories: ["Wonen, Huis & Tuin"],
    affiliateUrl: "https://bdt9.net/c/?si=1251&li=5695&wi=419930",
    commission: "4–6%",
    tags: ["gordijnen", "vloer", "wonen", "interieur", "raamdecoratie"],
  },
  {
    id: "leenbakker",
    name: "Leen Bakker",
    logoUrl: "https://www.google.com/s2/favicons?domain=leenbakker.nl&sz=64",
    description: "Betaalbare meubels en woonaccessoires. Voor elk interieur iets moois.",
    categories: ["Wonen, Huis & Tuin"],
    affiliateUrl: "https://bdt9.net/c/?si=1252&li=5696&wi=419930",
    commission: "4–5%",
    tags: ["meubels", "wonen", "slaapkamer", "woonkamer", "betaalbaar"],
  },
  {
    id: "kambukka",
    name: "Kambukka",
    logoUrl: "https://www.google.com/s2/favicons?domain=kambukka.com&sz=64",
    description: "Premium drinkflessen en thermosbekers voor onderweg en sport.",
    categories: ["Sport & Outdoor", "Wonen, Huis & Tuin"],
    affiliateUrl: "https://bdt9.net/c/?si=1794175&li=1794175&wi=419930",
    commission: "8–10%",
    tags: ["drinkfles", "thermos", "sport", "outdoor", "duurzaam"],
    featured: true,
  },
  {
    id: "eneco",
    name: "Eneco",
    logoUrl: "https://www.google.com/s2/favicons?domain=eneco.nl&sz=64",
    description: "Duurzame energie voor thuis. Groene stroom en gas van Nederlandse bodem.",
    categories: ["Energie", "Duurzaam"],
    affiliateUrl: "https://bdt9.net/c/?si=1253&li=5697&wi=419930",
    commission: "€20–€40 per contract",
    tags: ["energie", "stroom", "gas", "duurzaam", "groen"],
  },
  {
    id: "vattenfall",
    name: "Vattenfall",
    logoUrl: "https://www.google.com/s2/favicons?domain=vattenfall.nl&sz=64",
    description: "Groene energie, warmte en laadpalen voor elektrische auto's.",
    categories: ["Energie", "Duurzaam"],
    affiliateUrl: "https://bdt9.net/c/?si=1254&li=5698&wi=419930",
    commission: "€25 per contract",
    tags: ["energie", "stroom", "duurzaam", "zonnepanelen", "laadpaal"],
  },
  {
    id: "allekabels",
    name: "Allekabels.nl",
    logoUrl: "https://www.google.com/s2/favicons?domain=allekabels.nl&sz=64",
    description: "Meer dan 100.000 elektrische producten, kabels en accessoires.",
    categories: ["Electronica"],
    affiliateUrl: "https://bdt9.net/c/?si=1255&li=5699&wi=419930",
    commission: "3–5%",
    tags: ["kabels", "electronica", "accessoires", "oplaadkabels", "adapters"],
  },
  {
    id: "babypark",
    name: "Babypark",
    logoUrl: "https://www.google.com/s2/favicons?domain=babypark.nl&sz=64",
    description: "Alles voor je baby en peuter. Kinderwagens, autostoelen en babyspullen.",
    categories: ["Kinderen & Ouders"],
    affiliateUrl: "https://bdt9.net/c/?si=1256&li=5700&wi=419930",
    commission: "3–5%",
    tags: ["baby", "kinderwagen", "autostoel", "speelgoed", "ouders"],
  },
];
